<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
 Schema::create('title_submissions', function(Blueprint $t){$t->id();$t->foreignId('student_id')->constrained('users')->cascadeOnDelete();$t->foreignId('supervisor_id')->nullable()->constrained('users')->nullOnDelete();$t->string('title');$t->text('background')->nullable();$t->enum('status',['diajukan','disetujui','ditolak','revisi'])->default('diajukan');$t->text('notes')->nullable();$t->timestamp('approved_at')->nullable();$t->timestamps();});
 Schema::create('guidance_sessions', function(Blueprint $t){$t->id();$t->foreignId('student_id')->constrained('users')->cascadeOnDelete();$t->foreignId('supervisor_id')->constrained('users')->cascadeOnDelete();$t->enum('type',['proposal','skripsi'])->default('proposal');$t->date('session_date');$t->string('chapter')->nullable();$t->longText('student_note');$t->longText('supervisor_note')->nullable();$t->string('file_path')->nullable();$t->enum('status',['menunggu','direview','selesai','revisi'])->default('menunggu');$t->timestamps();});
 Schema::create('exam_registrations', function(Blueprint $t){$t->id();$t->foreignId('student_id')->constrained('users')->cascadeOnDelete();$t->enum('type',['seminar_proposal','sidang_skripsi']);$t->string('document_path')->nullable();$t->enum('status',['diajukan','diverifikasi','dijadwalkan','ditolak','selesai'])->default('diajukan');$t->dateTime('scheduled_at')->nullable();$t->string('room')->nullable();$t->text('notes')->nullable();$t->timestamps();});
 Schema::create('thesis_archives', function(Blueprint $t){$t->id();$t->foreignId('student_id')->constrained('users')->cascadeOnDelete();$t->string('title');$t->string('year',4);$t->string('keywords')->nullable();$t->string('abstract_path')->nullable();$t->string('file_path');$t->boolean('is_public')->default(true);$t->timestamps();});
 Schema::create('notifications', function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained('users')->cascadeOnDelete();$t->string('title');$t->text('message');$t->string('url')->nullable();$t->timestamp('read_at')->nullable();$t->timestamps();});
 } public function down(): void { foreach(['notifications','thesis_archives','exam_registrations','guidance_sessions','title_submissions'] as $table) Schema::dropIfExists($table); }};
